"""initial migration

Revision ID: 49e8b5200632
Revises: 
Create Date: 2026-06-27 03:52:39.996172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e8b5200632'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_methods',
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('method_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('payment_method_id'),
    sa.UniqueConstraint('method_name')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('buying_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('paybills',
    sa.Column('paybill_id', sa.Integer(), nullable=False),
    sa.Column('paybill_name', sa.String(length=100), nullable=False),
    sa.Column('paybill_number', sa.String(length=20), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.payment_method_id'], ),
    sa.PrimaryKeyConstraint('paybill_id')
    )
    op.create_table('sales',
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('selling_price_at_sale', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('buying_price_at_sale', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('paybill_id', sa.Integer(), nullable=True),
    sa.Column('sale_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paybill_id'], ['paybills.paybill_id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.payment_method_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('sale_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('paybills')
    op.drop_table('products')
    op.drop_table('payment_methods')
    # ### end Alembic commands ###
